const UsersActionTypes = {
  START_FETCHING: 'START_FETCHING',
  FAIL_FETCHING: 'FAIL_FETCHING',
  SEARCH_USER: 'SEARCH_USER',
  FETCH_USERS_END: 'FETCH_USERS_END',
  CLEAR_USERS: 'CLEAR_USERS',
  GET_REPOS: 'GET_REPOS',
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
};

export default UsersActionTypes;
